### ISSUE TITLE
Problems encountered when installing torchsparse

### ISSUE THREAD

**Issue by hlh2001** [MCG-NJU/LinK#2]
As mentioned in the paper, training with 3090 is feasible. Installing CUDA10.2 in 3090 is difficult. So I'm using CUDA11.3, Python3.7.10, pytorch1.10.1. The previous steps performed according to installation, and detectioin was added to PYTHONPATH, but when executing the last step, "pip install./torchsparse-u/", the error is as follows

Processing ./torchsparse-u
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: torchsparse
  Building wheel for torchsparse (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [112 lines of output]
...
      subprocess.CalledProcessError: Command '['which', 'c++']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torchsparse
  Running setup.py clean for torchsparse
Failed to build torchsparse
ERROR: Could not build wheels for torchsparse, which is required to install pyproject.toml-based projects

What might be the cause of this problem? Could you please give some reference configuration advice on using CUDA11.3 installation project environment on 3090?Besides,is the requirement.txt exactly the same as the requirement.txt in CenterPoint?

**Comment by inspirelt** [comment]
Hi. I just tried to re-install the ./torchsparse-u by ```pip install ./torchsparse-u/``` on a 3090 machine, and it worked with the attached environments. According to your log, it seems like an issue with the version of g++. My gcc/g++ versions are both 7.5.0, with the system version Ubuntu 18.04 (This should not have a significant impact, I guess). Hope this can help you.
[environments_for_cu113_seg.txt](https://github.com/MCG-NJU/LinK/files/12090206/environments_for_cu113_seg.txt)
[environments_for_cu113_det.txt](https://github.com/MCG-NJU/LinK/files/12090207/environments_for_cu113_det.txt)

**Comment by hlh2001** [comment]
Thank you very much for your answers. torchsparse is now installed. This is a problem with my system Settings,When I type ninja -v,it shows      ninja: error: loading 'build.ninja': No such file or directory.When I type ninja --version,it shows 1.11.1.git.kitware.jobserver-1.  My error was    ninja: build stopped: subcommand failed .So I made a change in setup.py,that is    cmdclass={'build_ext': BuildExtension.with_options(use_ninja=False)},then it works by pip install ./torchsparse-u/     besides,my gcc/g++ versions are both 9.5.0,with the system version Ubuntu 22.04.Thank you very much for your answers again!

**Comment by inspirelt** [comment]
That's Nice. Feel free to contact me if you have any other questions.

**Comment by hlh2001** [comment]
Hello, I wonder if APEX is necessary, as it shows no apex /no Tensorflow /Deformable Convolution not built.

**Comment by hlh2001** [comment]
Hello, I wonder if APEX is necessary, as it shows no apex /no Tensorflow /Deformable Convolution not built.

**Comment by hlh2001** [comment]
Hello, I wonder if APEX is necessary, as it shows no apex \no Tensorflow \Deformable Convolution not built.

**Comment by inspirelt** [comment]
Hi, APEX is optional and we did not install it.
