### ISSUE TITLE
how to visualize eval result

### ISSUE THREAD

**Issue by cyn-liu** [MCG-NJU/LinK#4]
when I run the follow command:
```bash
python -m torch.distributed.launch --nproc_per_node=4 --master_port 23456 ./tools/train.py \
  configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z_elkv3.py \
  --work_dir work_dirs/0075cbgs_cos3x7_group2_15+5 \
  --resume_from work_dirs/0075cbgs_cos3x7_group2/epoch_15.pth
```
I get a `prediction.pkl` in `work_dir work_dirs/0075cbgs_cos3x7_group2_15+5` directory, I want visualize the result, but I find the `./detection/tools/visual.py` can not work well, so where can  I find the scrip to visualize predict result.

**Comment by shawnding** [comment]
Hi, you can use `./detection/tools/demo.py` to visualize the detection result in top-down view. For 3D view, you can use open3d or mayavi to load and visualize the point cloud and detection boxes.
