### ISSUE TITLE
问一个问题

### ISSUE THREAD

**Issue by WenxuanLi-whu** [MCG-NJU/LinK#6]
只刷点云，刷了nuscenes数据集，效果还可以，这样投稿能中吗？我看你还专门刷了kitti，有谁告诉你的，请指点一下，我论文刚写完，准备投稿

**Comment by inspirelt** [comment]
最好多加点数据集, 如果暂时没法跑其它数据集, 就好好打磨论文吧.

**Comment by rubbish001** [comment]
兄弟，我看你的摘要真敢写啊Notably, we rank 1st on the public leaderboard of the 3D
detection benchmark of nuScenes (LiDAR track)，你投的时候focalformer已经到68.7%，怎么排第一了，我的68改怎么写
